repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        files: \.(py)$

      - id: mypy-docker
        name: mypy (in Docker)
        # Start a new container and run mypy on the code inside
        entry: docker run --rm hybrid-learning-hub-docker-app-server:latest mypy /backend/
        language: system
        files: \.(py)$
        pass_filenames: false
