"""removed salt from the user table

Revision ID: ccd5cdb69db3
Revises: a0742d69ad3d
Create Date: 2025-03-20 10:33:50.061530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccd5cdb69db3'
down_revision: Union[str, None] = 'a0742d69ad3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'status',
               existing_type=postgresql.ENUM('available', 'checked_out', 'reserved', name='bookstatusenum'),
               nullable=False)
    op.drop_column('users', 'salt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('books', 'status',
               existing_type=postgresql.ENUM('available', 'checked_out', 'reserved', name='bookstatusenum'),
               nullable=True)
    # ### end Alembic commands ###
