name: Run Test

on:
  workflow_call
#    outputs:
#      docker_tag:
#        description: "Docker Image Tag"
#        value: ${{ jobs.build_docker.outputs.docker_tag }}

jobs:
  build_docker:
    name: Build Docker Image for Tests
    uses: ./.github/workflows/build-docker.yaml
    secrets: inherit

  run_tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build_docker
    container:
      image: ${{ needs.build_docker.outputs.docker_tag }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.HYBRID_LEARNING_HUB_REGISTRY_PAT }}

    services:
      postgres:
        image: postgres:14
        options: >-
          --health-cmd "pg_isready"
          --health-interval 1s
          --health-timeout 3s
          --health-retries 30
        env:
          POSTGRES_PASSWORD: postgres

    steps:
      - name: Run Pytest
        run: |
          # Print the current directory
          pwd
          # List all files in the current directory
          ls -al
          # List all files in the parent directory to see if backend exists one level above
          ls -al ..
          # List all files recursively to see the full structure
          ls -alR
          pytest -v tests/ --cov=app/ --cov-report term-missing --durations=28
